name: props_provider
description: "Lightweight props provider for Flutter with fine-grained rebuilds powered by InheritedModel."
repository: https://github.com/lets-props/props_provider.git
version: 0.0.1

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
